In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys

In [2]:
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(project_root)

In [3]:
from scripts.pipeline import extract, load, transform, run_pipeline

In [4]:
df = extract()  # loads CSV from config.json
print("Raw data preview:")
display(df.head())

Loading raw data from: C:\Users\kusha\documents\shankar\data/customer_churn_dataset.csv
Raw data preview:

,customer_id,tenure,monthly_charges,total_charges,contract,payment_method,internet_service,tech_support,online_security,support_calls,churn
0,1,52,54.20,2818.40,Month-to-month,Credit,DSL,No,Yes,1,No
1,2,15,35.28,529.20,Month-to-month,Debit,DSL,No,No,2,No
2,3,72,78.24,5633.28,Month-to-month,Debit,DSL,No,No,0,No
3,4,61,80.24,4894.64,One year,Cash,Fiber,Yes,Yes,0,No
4,5,21,39.38,826.98,Month-to-month,UPI,Fiber,No,No,4,Yes

In [5]:
df.shape

(20000, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       20000 non-null  int64
 1   tenure            20000 non-null  int64
 2   monthly_charges   20000 non-null  float64
 3   total_charges     20000 non-null  float64
 4   contract          20000 non-null  object
 5   payment_method    20000 non-null  object
 6   internet_service  17987 non-null  object
 7   tech_support      20000 non-null  object
 8   online_security   20000 non-null  object
 9   support_calls     20000 non-null  int64
 10  churn             20000 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 1.7+ MB

In [7]:
df.describe()

,customer_id,tenure,monthly_charges,total_charges,support_calls
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,10000.500000,36.467450,70.010531,2543.979209,1.51255
std,5773.647028,20.773984,28.890239,1882.949804,1.23524
min,1.000000,1.000000,20.000000,20.230000,0.00000
25%,5000.750000,18.000000,45.210000,1045.837500,1.00000
50%,10000.500000,36.000000,70.090000,2096.495000,1.00000
75%,15000.250000,54.000000,95.072500,3690.337500,2.00000
max,20000.000000,72.000000,120.000000,8629.920000,8.00000

In [8]:
df.duplicated().sum()

0

In [9]:
df_clean = run_pipeline()

Loading raw data from: C:\Users\kusha\documents\shankar\data/customer_churn_dataset.csv
Transforming data: dropping duplicates and missing values
Saved cleaned data to: C:\Users\kusha\documents\shankar\data/clean_customer_data.csv
Pipeline complete!

In [10]:
df_clean

,customer_id,tenure,monthly_charges,total_charges,contract,payment_method,internet_service,tech_support,online_security,support_calls,churn
0,1,52,54.20,2818.40,Month-to-month,Credit,DSL,No,Yes,1,No
1,2,15,35.28,529.20,Month-to-month,Debit,DSL,No,No,2,No
2,3,72,78.24,5633.28,Month-to-month,Debit,DSL,No,No,0,No
3,4,61,80.24,4894.64,One year,Cash,Fiber,Yes,Yes,0,No
4,5,21,39.38,826.98,Month-to-month,UPI,Fiber,No,No,4,Yes
...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,36,69.51,2502.36,Two year,Cash,DSL,No,Yes,0,Yes
19996,19997,10,59.88,598.80,Month-to-month,UPI,Fiber,Yes,No,1,No
19997,19998,6,42.96,257.76,Month-to-month,Credit,Fiber,No,No,2,No
19998,19999,7,102.85,719.95,Month-to-month,Debit,DSL,Yes,No,2,No
19999,20000,31,44.84,1390.04,Two year,Credit,Fiber,Yes,No,1,Yes

In [11]:
df_clean.shape

(17987, 11)

In [12]:
df_clean.drop(columns = ['customer_id', 'total_charges'], inplace = True)

In [13]:
df_clean.isna().sum()

tenure              0
monthly_charges     0
contract            0
payment_method      0
internet_service    0
tech_support        0
online_security     0
support_calls       0
churn               0
dtype: int64

In [14]:
df_clean.head()

,tenure,monthly_charges,contract,payment_method,internet_service,tech_support,online_security,support_calls,churn
0,52,54.20,Month-to-month,Credit,DSL,No,Yes,1,No
1,15,35.28,Month-to-month,Debit,DSL,No,No,2,No
2,72,78.24,Month-to-month,Debit,DSL,No,No,0,No
3,61,80.24,One year,Cash,Fiber,Yes,Yes,0,No
4,21,39.38,Month-to-month,UPI,Fiber,No,No,4,Yes

In [15]:
X = df_clean.iloc[:,:-1].values
y = df_clean.iloc[:,-1].values

In [16]:
print(X)

[[52 54.2 'Month-to-month' ... 'No' 'Yes' 1]
 [15 35.28 'Month-to-month' ... 'No' 'No' 2]
 [72 78.24 'Month-to-month' ... 'No' 'No' 0]
 ...
 [6 42.96 'Month-to-month' ... 'No' 'No' 2]
 [7 102.85 'Month-to-month' ... 'Yes' 'No' 2]
 [31 44.84 'Two year' ... 'Yes' 'No' 1]]

In [17]:
print(y)

['No' 'No' 'No' ... 'No' 'No' 'Yes']

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [19]:
print(X_train.shape)

(14389, 8)

In [20]:
print(X_test.shape)

(3598, 8)

In [21]:
print(X[0])

[52 54.2 'Month-to-month' 'Credit' 'DSL' 'No' 'Yes' 1]

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[
    ('encoder', OneHotEncoder(),[2,3,4,5,6])
], remainder = 'passthrough')

In [23]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [2, 3, 4, 5, 6])])

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [25]:
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
pipeline = Pipeline(steps = [
    ('composer', ct),
    ('classifier',XGBClassifier())
])

In [26]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('composer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encoder', OneHotEncoder(),
                                                  [2, 3, 4, 5, 6])])),
                ('classifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               fea...ne,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [27]:
y_pred = pipeline.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 1, 1])

In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8407448582545859

In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
accuracies = cross_val_score(pipeline, X_train, y_train, cv = 5)

In [31]:
accuracies

array([0.84086171, 0.84016678, 0.83738707, 0.83564976, 0.83559263])

In [32]:
accuracies.mean()

0.8379315908708278

In [33]:
print("Accuricies",accuracies.std())

Accuricies 0.0022161080397211518